### Get all products
GET http://localhost:3000/products
Accept: application/json

### Get product by ID
GET http://localhost:3000/products/6741458a99f52ed91886955d
Accept: application/json

### Add a new product
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Great Product",
  "description": "Product Description",
  "price": 25.99,
  "category": "Electronics",
  "stock": 100
}

### Update a product by ID
PUT http://localhost:3000/products/6741458a99f52ed91886955d
Content-Type: application/json

{
  "name": "Updated Product Name",
  "description": "Updated Description",
  "price": 29.99,
  "category": "Home Appliances",
  "stock": 50
}

### Delete a product by ID
DELETE http://localhost:3000/products/6741458a99f52ed91886955d

### Get all products
GET https://cse341-project2-cmpr.onrender.com/products

### Get product by ID
GET https://cse341-project2-cmpr.onrender.com/products/6741458a99f52ed91886955d

### Add a new product
POST https://cse341-project2-cmpr.onrender.com/products
Content-Type: application/json

{
  "name": "Great Product",
  "description": "Product Description",
  "price": 25.99,
  "category": "Electronics",
  "stock": 100
}

### Update a product by ID
PUT https://cse341-project2-cmpr.onrender.com/products/6741458a99f52ed91886955d
Content-Type: application/json

{
  "name": "Updated Product Name",
  "description": "Updated Description",
  "price": 29.99,
  "category": "Home Appliances",
  "stock": 50
}

### Delete a product by ID
DELETE https://cse341-project2-cmpr.onrender.com/products/6741458a99f52ed91886955d

